### ISSUE TITLE
Cannot seem to see the close button for threads and downloads any more

### ISSUE THREAD

**Issue by chuyaguo2014** [caiceA/slack-black-theme#38]
After getting the new theme (about a week ago?) I noticed the close button is not as readable as before. Could you please take a look?

I am on MacOS 10.14.4 and I can confirm the same is happening on my windows machine. Here are some screenshots:

- For threads: 

![image](https://user-images.githubusercontent.com/9753313/55655444-45ede000-57c2-11e9-88c6-b66a614b7b3a.png)

- For downloads:

![image](https://user-images.githubusercontent.com/9753313/55655663-cb719000-57c2-11e9-8771-cba7e40028ad.png)

The close button for viewing Pinned items and Members of a channel is working correctly though. 

Please let me know if there's any additional information I can provide. Thank you!

**Comment by caiceA** [comment]
@chuyaguo2014  get the latest file from the server

**Comment by MyGitUsrname** [comment]
@caiceA I got the latest file today from github (not http://neckcode.com/slack/ssb-interop.js.zip) and the issue is still apparent, are the 2 versions different? Slack for Mac Mojave 10.14.3 version 3.4.0
<img width="378" alt="Screen Shot 2019-05-08 at 10 36 21 AM" src="https://user-images.githubusercontent.com/22553515/57337503-adaa9880-717d-11e9-9911-13aed6851aa9.png">

**Comment by caiceA** [comment]
@Alqueza yes one server its latest
